<?php

return [
    [
        'name' => 'Maiale agrodolce',
        'description'=> 'Pezzi di maiale teneri e succulenti marinati in una salsa agrodolce, con una combinazione di sapori dolci e aspri.',
        'price' => 12.50,
        'img' => 'https://www.fattoincasadabenedetta.it/wp-content/uploads/2022/03/copertina-sito-maiale-in-agrodolce.jpg',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Pollo al limone',
        'description'=> 'Bocconcini di pollo teneri e succulenti cotti in una salsa fresca e vivace al limone, che dona un sapore brillante e aromatico al piatto.',
        'price' => 11.75,
        'img' => 'https://www.cucchiaio.it/content/dam/cucchiaio/it/ricette/2023/12/straccetti-pollo-limone/Straccetti_di_pollo_limone_orizz.jpg',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Riso fritto con gamberi',
        'description'=> 'Riso cotto al dente saltato in padella con gamberi succulenti, uova e una miscela di verdure fresche, il tutto condito con salsa di soia e spezie.',
        'price' => 14.25,
        'img' => 'https://recipeimages.migros.ch/crop/v-w-1200-h-630-a-center_center/fde2b155c8486a9fca8bad4e194af20846b10547/riso-fritto-con-cavolo-cinese-e-gamberetti-0-16-9.jpg',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Manzo in salsa di ostriche',
        'description'=> 'Fettine di manzo tenere e succulente immerse in una salsa ricca e saporita a base di ostriche, arricchita con verdure croccanti.',
        'price' => 15.50,
        'img' => 'https://ayam.fr/images/Ayam-Recipe-2019/main-pix/boeuf_sauce_huitre.png',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Gnocchi saltati con verdure',
        'description'=> 'Gnocchi di patate fatti in casa saltati in padella con una varietà di verdure fresche, come zucchine, pomodori e spinaci, conditi con erbe aromatiche e formaggio.',
        'price' => 13.00,
        'img' => 'https://tempodicottura.it/wp-content/uploads/2022/07/gnocchi-cinesi-alle-verdure.jpg',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Kebab di pollo con riso',
        'description'=> 'Deliziosi bocconcini di pollo marinati e grigliati, serviti con riso aromatizzato e condito con spezie esotiche.',
        'price' => 8.50,
        'img' => 'https://i2.wp.com/www.antoniettapolcaro.it/wp-content/uploads/2023/08/piadina-kebab-pollo-antonietta-polcaro.jpg?fit=1200%2C800&ssl=1&resize=1280%2C720',
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Kebab di agnello con insalata',
        'description'=> 'Gustoso kebab di agnello preparato con carne di agnello macinata, spezie mediterranee e erbe fresche, accompagnato da croccante insalata mista.',
        'price' => 9.75,
        'img' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4me1eF1TyiIrGb22FUga0EC4UvHSdZP84gw&usqp=CAU',
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Kebab vegetariano con falafel',
        'description'=> 'Una deliziosa alternativa vegetariana con falafel croccanti e spezie esotiche, avvolte in un morbido pane pita e accompagnate da verdure fresche e salse cremose.',
        'price' => 7.90,
        'img' => 'https://i0.wp.com/citymagazine.si/wp-content/uploads/2023/03/falafel-and-fresh-vegetables-in-pita-bread-2021-08-31-13-44-18-utc.jpg?fit=5472%2C3648&ssl=1',
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Piadina con kebab di tacchino',
        'description'=> 'Una piadina calda e fragrante farcita con succulento kebab di tacchino marinato, accompagnato da verdure croccanti e salse gustose.',
        'price' => 8.25,
        'img' => 'https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2019/09/1569403721_fb9a1b57279d9f8758afa897fa7614501268f8a0-1569318426.jpg?width=1280&height=720&quality=90',
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Kebab di manzo con patatine e salse',
        'description'=> 'Saporito kebab di manzo preparato con carne di manzo macinata e spezie orientali, servito con patatine croccanti e una selezione di salse deliziose.',
        'price' => 10.50,
        'img' => 'https://milleeunanottelivakebab.it/wp-content/uploads/2022/11/kebab-1.jpg',
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Tacos al pastor',
        'description'=> 'Tortillas di mais ripiene di succulenta carne di maiale marinata con spezie messicane e arrostita alla griglia, servite con cipolle, coriandolo e salsa piccante.',
        'price' => 9.50,
        'img' => 'https://mysliceofmexico.files.wordpress.com/2020/05/000-tacos-al-pastor.jpg?w=1200',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Guacamole con nachos',
        'description'=> 'Preparato con avocado maturo, pomodoro, cipolla, coriandolo e lime, il nostro guacamole è servito con croccanti nachos di mais per una combinazione di sapori freschi e croccanti.',
        'price' => 6.75,
        'img' => 'https://www.fattoincasadabenedetta.it/wp-content/uploads/2022/02/AdobeStock_60789987.jpeg',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Enchiladas di pollo',
        'description'=> 'Tortillas di mais ripiene di succulento pollo al taco, avvolte e coperte da una salsa di pomodoro e peperoncino, gratinate con formaggio fuso e servite con panna acida.',
        'price' => 11.25,
        'img' => 'https://www.turismo.it/typo3temp/pics/3ccfa45259.jpg',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Burritos con carne di manzo',
        'description'=> 'Generose porzioni di carne di manzo marinata e cotta lentamente, avvolte in una morbida tortilla di farina con riso, fagioli, formaggio, salsa e guacamole.',
        'price' => 12.90,
        'img' => 'https://www.melarossa.it/wp-content/uploads/2021/07/burrito-messicano.jpg',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Quesadillas con formaggio e fagioli',
        'description'=> 'Tortillas di farina farcite con formaggio fuso cremoso e fagioli neri speziati, arrostite fino a ottenere una crosta dorata, servite con panna acida e salsa.',
        'price' => 8.95,
        'img' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2020/07/quesadillas-la-ricetta-originale-1280x720.jpg',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Spaghetti alla carbonara',
        'description'=> 'Spaghetti al dente conditi con uova, guanciale, pecorino romano e pepe nero macinato fresco, per un piatto cremoso e ricco di sapori.',
        'price' => 10.50,
        'img' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbas_KUeQ_dJxNRn0_PK5z3MiZvVYzYPewLfjB4aNMZF-yoHF12FUcGQsk9g8q91wbCAM&usqp=CAU',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Ossobuco alla milanese',
        'description'=> 'Ossobuco di vitello cotto lentamente in un sugo ricco di pomodoro, vino bianco, sedano, carote e cipolle, servito con gremolata fresca e polenta cremosa.',
        'price' => 18.90,
        'img' => 'https://cdn.cook.stbm.it/thumbnails/ricette/0/780/hd750x421.jpg',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Risotto ai funghi',
        'description'=> 'Risotto cremoso cotto lentamente con funghi porcini freschi, scalogno, vino bianco e una generosa dose di parmigiano reggiano, per un piatto ricco e avvolgente.',
        'price' => 12.25,
        'img' => 'https://www.fortunatiantonio.it/wp-content/uploads/2015/05/shutterstock_116404021.jpg',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Lasagne alla bolognese',
        'description'=> 'Strati di pasta fresca alternati con una salsa bolognese ricca e saporita, besciamella cremosa e parmigiano reggiano, cotti al forno fino a ottenere una crosta dorata.',
        'price' => 13.90,
        'img' => 'https://www.conad.it/assets/images/ricette/viabagutta/logo-rosso/lasagne-alla-bolognese.jpg?_u=6d9f70e7cdbb81bff44b9a40a57cfd411f382ebd',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Tagliatelle al ragù',
        'description'=> 'Tagliatelle fresche condite con un ragù di carne di manzo e maiale cotto lentamente con pomodori, carote, sedano e vino rosso, per un piatto succulento e avvolgente.',
        'price' => 11.50,
        'img' => 'https://www.giallozafferano.it/images/5-577/Tagliatelle-al-ragu-bianco_450x300.jpg',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Salmone alla griglia',
        'description'=> 'Filetto di salmone fresco e succulento, marinato con erbe aromatiche e succo di limone, quindi grigliato alla perfezione per un sapore leggermente affumicato e una consistenza morbida.',
        'price' => 16.50,
        'img' => 'https://media.grandchef.net/ricette/salmone-alla-griglia/galleria/salmone-alla-griglia.jpg',
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Zuppa di pesce',
        'description'=> 'Una miscela ricca e avvolgente di pesce fresco, cozze, vongole e calamari cotti lentamente in un brodo di pomodoro aromatizzato con aglio, prezzemolo e peperoncino.',
        'price' => 18.75,
        'img' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2009/11/ricetta-zuppa-pesce-misto/_jcr_content/header-par/image_single.img.jpg/1624446822462.jpg',
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Filetto di branzino al forno',
        'description'=> 'Filetto di branzino fresco cotto al forno con olive, pomodorini, capperi e origano, servito su un letto di verdure al vapore per un piatto leggero ma soddisfacente.',
        'price' => 19.90,
        'img' => 'https://www.donnamoderna.com/content/uploads/2013/04/filetti-di-branzino-alle-arance-725x545.jpg',
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Tonno alla griglia',
        'description'=> 'Fresco filetto di tonno marinato con olio d oliva, limone e erbe aromatiche, quindi grigliato alla perfezione per ottenere una crosta croccante all esterno e una consistenza succosa all interno.',
        'price' => 21.50,
        'img' => 'https://blog.giallozafferano.it/pierobenigni/wp-content/uploads/2020/04/IMG_2847-4-960x640.jpg',
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Insalata di tonno e fagioli',
        'description'=> 'Insalata fresca e leggera preparata con tonno in scatola, fagioli cannellini, pomodorini, cipolla rossa, prezzemolo e condita con olio d oliva e succo di limone.',
        'price' => 14.25,
        'img' => 'https://www.ricettedigabri.it/wp-content/uploads/2022/06/insalata-tonno-fagioli-piatti-freddi-portare-mare-gabri-scaled.jpg',
        'restaurant_id' => 9,

    ],
    [
        'name' => 'Filetto di manzo alla griglia',
        'description'=> 'Filetto di manzo di alta qualità grigliato alla perfezione, servito con una salsa di vino rosso ridotta e accompagnato da verdure grigliate e patate arrosto.',
        'price' => 26.90,
        'img' => 'https://i.pinimg.com/736x/2c/e4/8c/2ce48c5c50b34a35b48106f7cdbd499c.jpg',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Braciola di maiale ripiena',
        'description'=> 'Braciola di maiale farcita con formaggio, prosciutto crudo e erbe aromatiche, quindi rosolata e cotta lentamente in un sugo di pomodoro e vino bianco, servita con polenta o purea di patate.',
        'price' => 19.75,
        'img' => 'placeholder',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Costolette di agnello alla griglia',
        'description'=> 'Costolette di agnello marinato con aglio, rosmarino e olio d oliva, quindi grigliate alla perfezione e servite con un contorno di couscous e verdure alla griglia.',
        'price' => 23.50,
        'img' => 'placeholder',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Spezzatino di manzo',
        'description'=> 'Spezzatino di manzo cotto a fuoco lento con carote, patate, cipolle e sedano in un brodo di carne ricco e aromatico, servito con una spruzzata di prezzemolo fresco.',
        'price' => 17.90,
        'img' => 'placeholder',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Brasato di vitello al vino rosso',
        'description'=> 'Brasato di vitello cotto lentamente in una salsa al vino rosso con carote, cipolle, sedano e aglio, fino a quando la carne diventa tenera e succulenta, servita con purè di patate.',
        'price' => 21.50,
        'img' => 'placeholder',
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Hot Dog con crauti',
        'description'=> 'Salsiccia di maiale affumicata servita in un morbido panino con ketchup, senape e crauti freschi, accompagnato da patatine fritte.',
        'price' => 8.50,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Chicken Nuggets con salsa agrodolce',
        'description'=> 'Pezzi di petto di pollo impanati e fritti fino a ottenere una crosta dorata e croccante, serviti con una salsa agrodolce e patatine fritte.',
        'price' => 7.75,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Wrap di pollo con insalata',
        'description'=> 'Tortilla farcita con bocconcini di pollo grigliato, lattuga croccante, pomodori a fette, formaggio cheddar grattugiato e salsa al ranch, servita con patatine fritte.',
        'price' => 9.25,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Fish and Chips',
        'description'=> 'Filetto di merluzzo fresco immerso in una pastella leggera e fritto fino a ottenere una crosta dorata e croccante, servito con patatine fritte e salsa tartara.',
        'price' => 10.50,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Wrap di salmone affumicato',
        'description'=> 'Tortilla farcita con fette di salmone affumicato, formaggio cremoso, lattuga, cetrioli a fette e salsa allo yogurt e erba cipollina, servita con patatine fritte.',
        'price' => 12.90,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Pizza Quattro Stagioni',
        'description'=> 'Divisa in quattro sezioni, questa pizza è farcita con pomodoro, mozzarella, funghi, prosciutto cotto, carciofi e olive nere, offrendo una combinazione di sapori che rappresentano le quattro stagioni.',
        'price' => 11.90,
        'img' => 'placeholder',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Bufalina',
        'description'=> 'Una pizza classica con una semplice ma deliziosa combinazione di pomodoro, mozzarella di bufala fresca a fette, basilico fresco e un filo d olio d oliva extravergine.',
        'price' => 12.50,
        'img' => 'placeholder',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Diavola',
        'description'=> 'Per gli amanti del piccante, questa pizza è farcita con pomodoro, mozzarella, salame piccante e peperoncini freschi o peperoncini rossi, per un tocco extra di calore.',
        'price' => 10.75,
        'img' => 'placeholder',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Capricciosa',
        'description'=> 'Una pizza ricca e abbondante con pomodoro, mozzarella, prosciutto cotto, funghi, carciofi, olive nere e basilico, per soddisfare tutti i gusti e le voglie.',
        'price' => 13.25,
        'img' => 'placeholder',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Bianca con Patate e Rosmarino',
        'description'=> 'Senza salsa di pomodoro, questa pizza è coperta con mozzarella, patate a fette sottili, rosmarino fresco e un filo d olio d oliva, offrendo un sapore rustico e aromatico.',
        'price' => 11.50,
        'img' => 'placeholder',
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Hamburger con formaggio e bacon',
        'description'=> 'Un classico intramontabile, questo hamburger è servito su un morbido panino con un succulento hamburger di manzo, formaggio fuso, fette di bacon croccante, lattuga, pomodoro e maionese.',
        'price' => 11.90,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Hamburger BBQ con cipolle croccanti',
        'description'=> 'Hamburger alla griglia glassato con salsa barbecue affumicata, servito su un panino tostato con cipolle croccanti fritte, lattuga, pomodoro e formaggio cheddar fuso.',
        'price' => 12.50,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Hamburger di pollo alla griglia',
        'description'=> 'Un alternativa leggera e saporita all hamburger di manzo, questo hamburger è preparato con petto di pollo alla griglia, lattuga croccante, pomodoro, cipolla rossa, maionese e senape.',
        'price' => 10.75,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Hamburger di manzo gourmet con formaggio blu',
        'description'=> 'Un hamburger gourmet preparato con carne di manzo di alta qualità, servito su un panino alla cipolla tostato, con formaggio blu saporito, cipolla caramellata, lattuga croccante e maionese al pepe nero.',
        'price' => 14.90,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Hamburger con funghi e formaggio di capra',
        'description'=> 'Un opzione gourmet, questo hamburger è farcito con funghi grigliati, formaggio di capra cremoso, rucola fresca, pomodoro affettato e una spruzzata di aceto balsamico, servito su un panino ai cereali.',
        'price' => 11.50,
        'img' => 'placeholder',
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Dragon Roll',
        'description'=> 'Un roll di sushi farcito con gambero tempura, avocado e cetriolo, avvolto in fettine di avocado e decorato con salsa unagi dolce e semi di sesamo.',
        'price' => 15.50,
        'img' => 'placeholder',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Rainbow Roll',
        'description'=> 'Un roll di sushi con un mix di pesce sashimi, come salmone, tonno e gambero, avvolto in fogli di alga nori e riso, decorato con strisce di avocado e salsa dolce.',
        'price' => 16.90,
        'img' => 'placeholder',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Spider Roll',
        'description'=> 'Un roll di sushi farcito con gambero tempura, avocado, lattuga e maionese piccante, avvolto in frittura di tempura croccante e servito con salsa ponzu.',
        'price' => 14.75,
        'img' => 'placeholder',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Volcano Roll',
        'description'=> 'Un roll di sushi farcito con gambero tempura, anatra glassata, avocado e formaggio cremoso, avvolto in frittura di tempura croccante e servito con una spruzzata di salsa piccante.',
        'price' => 17.25,
        'img' => 'placeholder',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Caterpillar Roll',
        'description'=> 'Un roll di sushi farcito con anguilla alla griglia, avocado e cetriolo, avvolto in fettine di avocado e decorato con salsa unagi dolce e semi di sesamo.',
        'price' => 18.50,
        'img' => 'placeholder',
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Tiramisù',
        'description'=> 'Un classico dessert italiano composto da strati di savoiardi inzuppati nel caffè, alternati con una crema di mascarpone leggera e guarniti con cacao amaro in polvere.',
        'price' => 7.50,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Cheesecake alla fragola',
        'description'=> 'Una torta al formaggio cremoso, arricchita con una dolce salsa di fragole fresche e decorata con morbidi pezzi di fragola, per un dessert deliziosamente indulgente.',
        'price' => 8.90,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Cannoli siciliani',
        'description'=> 'Deliziose conchiglie di pasta fritte, ripiene di una ricca crema di ricotta dolce arricchita con gocce di cioccolato e scorza d arancia candita.',
        'price' => 6.75,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Torta al cioccolato fondente',
        'description'=> 'Una torta al cioccolato ricca e decadente, fatta con cioccolato fondente di alta qualità, burro, zucchero e uova, servita con una salsa al cioccolato calda.',
        'price' => 9.25,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Pastiera napoletana',
        'description'=> 'Una torta tradizionale della cucina napoletana, composta da una crosta di pasta frolla e un ripieno di ricotta fresca, grano cotto, canditi e acqua di fiori d arancio.',
        'price' => 7.75,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Gelato alla stracciatella',
        'description'=> 'Un classico gelato italiano composto da una base di gelato alla crema arricchita con scaglie di cioccolato fondente, che si fondono delicatamente in bocca con ogni morso.',
        'price' => 5.50,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Gelato alla nocciola',
        'description'=> 'Un gelato cremoso e vellutato, fatto con latte fresco e nocciola tostata, che regala un sapore ricco e avvolgente, perfetto per gli amanti della frutta secca.',
        'price' => 5.75,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Gelato al pistacchio',
        'description'=> 'Un gelato dalla consistenza cremosa e il gusto intenso, preparato con pistacchi di alta qualità, che conferiscono al gelato un colore verde brillante e un sapore irresistibile.',
        'price' => 6.25,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Gelato al limone',
        'description'=> 'Un gelato fresco e rinfrescante, preparato con succo di limone appena spremuto e scorze di limone grattugiate, che regalano un sapore acidulo e vivace.',
        'price' => 5.25,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Gelato alla fragola',
        'description'=> 'Un gelato delicato e profumato, fatto con fragole fresche e zucchero, che offre un sapore dolce e fruttato, perfetto per soddisfare la voglia di dolcezza.',
        'price' => 5.50,
        'img' => 'placeholder',
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Pad Thai Vegano',
        'description'=> 'Un piatto tradizionale thailandese preparato con noodles di riso saltati in padella con tofu marinato, verdure croccanti come peperoni, carote e cipolle, arricchito con una salsa agrodolce a base di tamarindo e guarnito con arachidi tritate e lime.',
        'price' => 12.90,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Curry di ceci e patate dolci',
        'description'=> 'Un curry cremoso e aromatico preparato con ceci teneri, patate dolci, pomodori maturi, latte di cocco e una miscela di spezie come curcuma, coriandolo e cumino, servito con riso basmati al vapore e coriandolo fresco per una fragranza irresistibile.',
        'price' => 11.50,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Bowl di Buddha',
        'description'=> 'Un piatto sano e colorato composto da una base di quinoa o riso integrale, accompagnato da una varietà di verdure grigliate o cotte al vapore, come broccoli, cavolfiore, carote, avocado e cavolo rosso, condito con una vinaigrette leggera a base di olio d oliva e limone.',
        'price' => 10.75,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Hummus Bowl con Falafel',
        'description'=> 'Una ciotola abbondante di hummus di ceci fatti in casa, arricchita con olive kalamata, pomodori a cubetti, cetrioli, cipolla rossa marinata e prezzemolo fresco, accompagnata da falafel croccanti e una spruzzata di olio d oliva.',
        'price' => 11.90,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Zuppa di lenticchie e verdure',
        'description'=> 'Una zuppa calda e avvolgente preparata con lenticchie coralline, patate, carote, sedano, pomodori maturi e una miscela di erbe aromatiche come timo e rosmarino, arricchita con un pizzico di paprika affumicata per un sapore extra.',
        'price' => 9.50,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Frittata di verdure',
        'description'=> 'Una frittata leggera e soffice preparata con uova, zucchine, peperoni, cipolle e pomodori freschi, arricchita con formaggio grattugiato e prezzemolo, cotta al forno fino a doratura.',
        'price' => 10.50,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Insalata Greca',
        'description'=> 'Un insalata fresca e colorata preparata con pomodori, cetrioli, olive kalamata, cipolla rossa e feta greca, condita con olio d oliva, origano e succo di limone, servita con pane tostato all aglio.',
        'price' => 9.90,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Lasagne alle verdure',
        'description'=> 'Uno strato cremoso di pasta lasagna farcito con zucchine grigliate, melanzane, peperoni, spinaci e salsa di pomodoro fresca, alternati con strati di besciamella e formaggio, cotto al forno fino a doratura.',
        'price' => 12.75,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Tacos vegetariani',
        'description'=> 'Tortillas di mais farcite con fagioli neri, mais, peperoni, cipolle, avocado a fette e salsa al lime e coriandolo, per un pasto veloce e saporito adatto a tutti i palati.',
        'price' => 11.25,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Risotto ai funghi',
        'description'=> 'Un risotto cremoso e avvolgente preparato con riso arborio, funghi misti, cipolle, aglio, vino bianco e brodo vegetale, finito con una spruzzata di prezzemolo fresco e parmigiano grattugiato.',
        'price' => 13.50,
        'img' => 'placeholder',
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Pasta Senza Glutine alla Carbonara',
        'description'=> 'Una deliziosa pasta senza glutine condita con una cremosa salsa alla carbonara preparata con uova, pancetta croccante, pecorino romano e pepe nero macinato fresco.',
        'price' => 14.90,
        'img' => 'placeholder',
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Lasagne Senza Glutine al Ragù',
        'description'=> 'Strati di pasta senza glutine intercalati con ragù di carne ricco e saporito, salsa bechamel e formaggio, cotti al forno fino a ottenere una doratura croccante.',
        'price' => 16.50,
        'img' => 'placeholder',
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Pizza Senza Glutine Margherita',
        'description'=> 'Una pizza senza glutine con una base sottile e croccante, coperta con salsa di pomodoro, mozzarella fresca, basilico e un filo d olio d oliva extravergine.',
        'price' => 12.75,
        'img' => 'placeholder',
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Gnocchi Senza Glutine al Pesto',
        'description'=> 'Gnocchi di patate senza glutine serviti con una deliziosa salsa di pesto preparata con basilico fresco, pinoli, aglio, olio d oliva e parmigiano grattugiato.',
        'price' => 15.25,
        'img' => 'placeholder',
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Spaghetti Senza Glutine alla Puttanesca',
        'description'=> 'Spaghetti senza glutine conditi con una salsa puttanesca ricca e saporita preparata con pomodori, acciughe, capperi, olive nere, aglio, peperoncino e prezzemolo.',
        'price' => 13.50,
        'img' => 'placeholder',
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Lasagne di Verdure',
        'description'=> 'Uno strato di pasta lasagna senza glutine intercalato con verdure grigliate come zucchine, melanzane, peperoni e carote, arricchito con salsa di pomodoro, besciamella e formaggio, cotto al forno fino a ottenere una doratura croccante.',
        'price' => 16.90,
        'img' => 'placeholder',
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Risotto ai Funghi Porcini',
        'description'=> 'Un risotto cremoso preparato con riso carnaroli, funghi porcini freschi o secchi, cipolla, aglio, vino bianco e brodo vegetale, finito con prezzemolo fresco e una spruzzata di parmigiano vegano.',
        'price' => 18.50,
        'img' => 'placeholder',
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Gnocchi di Patate con Pesto di Rucola',
        'description'=> 'Gnocchi di patate senza glutine serviti con una deliziosa salsa di pesto preparata con rucola fresca, pinoli, aglio, olio d oliva e parmigiano vegano, per un piatto aromatico e saporito.',
        'price' => 15.75,
        'img' => 'placeholder',
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Melanzane alla Parmigiana',
        'description'=> 'Fette di melanzane grigliate o fritte, alternate con strati di salsa di pomodoro, mozzarella vegana e basilico fresco, cotto al forno fino a ottenere una doratura croccante e un cuore cremoso.',
        'price' => 14.90,
        'img' => 'placeholder',
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Orecchiette con Broccoli e Salsiccia Vegetariana',
        'description'=> 'Orecchiette senza glutine servite con broccoli al vapore, salsiccia vegetale a base di lenticchie o fagioli, aglio, peperoncino e prezzemolo, condite con olio d oliva e una spruzzata di pepe nero.',
        'price' => 17.25,
        'img' => 'placeholder',
        'restaurant_id' => 8,
    ],
];
